### ISSUE TITLE
Can't open an issue from Gerrit

### ISSUE THREAD

**Issue by arafel** [borysf/SublimeGerrit#1]
Hi

Thanks for writing SublimeGerrit - it's nice to be able to interact with it without leaving ST. :-)

Unfortunately I'm having a problem with the issue view - I can see the list of open issues, but as soon as I try to open one there's a backtrace shown on the console, as below. Could you let me know if it's a known issue, or if you need more debug trace, anything like that? This is ST3 build 3083, Sublime Gerrit 1.0.13.

(I do have a fuller debug log, but it'll need sanitising before I can attach it)

('GET', '/changes/?O=1&n=50&q=status:open+AND+-is:draft')
('GET', '/changes/154/detail?o=DOWNLOAD_COMMANDS&o=ALL_REVISIONS&o=DETAILED_LABELS&o=CURRENT_ACTIONS&o=MESSAGES&o=DETAILED_ACCOUNTS&o=ALL_COMMITS&o=ALL_FILES&o=DRAFT_COMMENTS')
('GET', '/changes/154/revisions/1/comments', None, True)
('GET', '/changes/154/revisions/1/drafts', None, True)
('GET', '/changes/154/revisions/1/submit_type')
Exception in thread Thread-13:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "core.resources in /home/pwalker/.config/sublime-text-3/Installed
  Packages/SublimeGerrit.sublime-package", line 64, in run
  File "core.change_view in
  /home/pwalker/.config/sublime-text-3/Installed
  Packages/SublimeGerrit.sublime-package", line 201, in do_render
  File "core.change_view in
  /home/pwalker/.config/sublime-text-3/Installed
  Packages/SublimeGerrit.sublime-package", line 692, in has_action
KeyError: 'enabled'

Thanks
Paul

**Comment by borysf** [comment]
Thanks. Should be better now.

**Comment by arafel** [comment]
Yep, that's fixed it - thanks, that's an amazingly quick response. :-)
