### ISSUE TITLE
Cannot store the "basic setting->Project" within config file

### ISSUE THREAD

**Issue by kuien** [borysf/SublimeGerrit#4]
Each time I restart sublime-text 3, I need to set the Project (in basic setting) manually, because I focus on an individual project rather than the whole gerrit server.

Any way to store this setting permanently? for example, store `project` and `branch` into file `SublimeGerrit.sublime-settings`? thanks.

**Comment by borys-stratoscale** [comment]
Hi. You need to have Sublime's project created first: Project -> Save Project As... Then you can define the SublimeGerrit's Project settings. Now these settings will be assigned to this Sublime's project permanently. Whenever you open this project, the settings will be read and applied. This way you can have many Gerrit's projects configured for individual Sublime's projects.

**Comment by borysf** [comment]
Hi. You need to have Sublime's project created first: Project -> Save Project As... Then you can define the SublimeGerrit's Project settings. Now these settings will be assigned to this Sublime's project permanently. Whenever you open this project, the settings will be read and applied. This way you can have many Gerrit's projects configured for individual Sublime's projects.
